name: GitHub Actions Test
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  backend-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v3

    - name: Install dependencies & Test
      run: npm install && npm run test
